---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 3402196900-xx5RwcdwJ1WovULzgJQnLIFaG2CpaSSvCCHfCLE
:access_token_secret: ThyrF2WYGbDPY1QadHarcz5fIyzl8XAzFYnSjtZddir3i
